version: '3'
services:
  identidock:
    build: .
    ports:
      - '5000:5000'
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    # TODO linksから変更する
    links:
      - dnmonster

  dnmonster:
    image: amouat/dnmonster:1.0